import 'client.dart';
import 'enums.dart';

/// Le carnet d'adresses livre avec l'application.
///
/// Ce sont les clients sous contrat, repris du recapitulatif tenu par
/// l'entreprise. Ils servent de point de depart : le carnet s'enrichit
/// ensuite depuis l'application, et chaque fiche reste modifiable.
///
/// L'adresse ne porte pas de code postal — le recapitulatif n'en avait pas.
/// Il se saisit au premier rapport, et le carnet le retient.
const List<Client> defaultClients = <Client>[
  Client(
    id: 'anse-sdc-porte-du-beaujolais-maison-du-rhone',
    name: 'SDC Porte du Beaujolais - Maison du Rhône',
    addressLine: '1, Avenue du Général Leclerc',
    city: 'Anse',
    phone: '06 62 28 36 50',
    email: 'syndic@dpl-immo.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'beynost-mr-gabrici',
    name: 'Mr GABRICI',
    addressLine: '132, Chemin de Halage',
    city: 'Beynost',
    phone: '06 71 06 36 44',
    email: 'mickael.gabrici@gmail.com',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'brindas-mme-roy-veronique-mr-devillers-raphael',
    name: 'Mme ROY Véronique & Mr DEVILLERS Raphaël',
    addressLine: '10, Chemin des Hoteaux',
    city: 'Brindas',
    phone: '06 76 75 13 05',
    email: 'r.devillers@amalgame-alu.fr / veroy4@gmail.com',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'caluire-cuire-mr-roucher-gregory',
    name: 'Mr ROUCHER Grégory',
    addressLine: '16, avenue des Cottages',
    city: 'Caluire & Cuire',
    phone: '06 85 11 81 39',
    email: 'gregory.roucher@hotmail.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'chasselay-mr-veleat',
    name: 'Mr VELEAT',
    addressLine: '1040, Chemin des Alouettes',
    city: 'Chasselay',
    phone: '06 50 47 61 31',
    email: 'antoineveleat@gmail.com',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'chiroubles-mr-ekstrom-john',
    name: 'Mr EKSTRÖM John',
    addressLine: '26 Allée des Géraniums',
    city: 'Chiroubles',
    phone: '070-630 39 00',
    email: 'John.Ekstroem@perstorp.com',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'denice-mr-soyleyen-ersen',
    name: 'Mr SOYLEYEN Ersen',
    addressLine: '30, Route du Rivolet',
    city: 'Denicé',
    phone: '06 04 52 72 29',
    email: 'soyleyen_ersen@hotmail.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'dommartin-mr-ramella-matthieu',
    name: 'Mr RAMELLA Matthieu',
    addressLine: '1180, Route du Pont de Reyre',
    city: 'Dommartin',
    phone: '07 69 11 91 76',
    email: 'matthieu.ramella@gmail.com',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'decines-association-la-roseraie',
    name: 'Association "La Roseraie"',
    addressLine: '26, Rue Salvatore Allende',
    city: 'Décines',
    phone: '06 01 32 20 32',
    email: 'pascal.leconte@paredes.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'fareins-mme-legendre-nathalie',
    name: 'Mme LEGENDRE Nathalie',
    addressLine: '436, Chemin du Mas du Puits',
    city: 'Fareins',
    phone: '06 45 20 18 01',
    email: 'nathalielegendre1107@gmail.com',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'fontaines-sur-saone-mr-chapuis',
    name: 'Mr CHAPUIS',
    addressLine: '36, Quai Jean-Baptiste Simon',
    city: 'Fontaines Sur Saône',
    phone: '06 23 51 72 68',
    email: 'cyrilchapuis21@gmail.com',
    contracts: {ReportKind.filtreCompact, ReportKind.posteRelevage},
  ),
  Client(
    id: 'frans-mme-marcelle-emilienne',
    name: 'Mme MARCELLE Emilienne',
    addressLine: '51, Chemin de la Gravière',
    city: 'Frans',
    phone: '06 89 65 94 13',
    email: 'sandrineg.1969@outlook.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'genouilleux-sdc-chateau-gaillard',
    name: 'SDC Château Gaillard',
    addressLine: 'Chemin de Château gaillard',
    city: 'Genouilleux',
    phone: '06 20 69 70 87',
    email: 'sophie.jalicon@oralia.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'la-mulatiere-mme-masquelier',
    name: 'Mme MASQUELIER',
    addressLine: '99 - 101, Chemin de Fontanière',
    city: 'La Mulatière',
    phone: '06 86 95 62 42',
    email: 'georgesmasquelier@gmail.com',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'la-tour-de-salvagny-mr-tripon-colin',
    name: 'Mr TRIPON Colin',
    addressLine: '48 Bis, Rue de la Gare',
    city: 'La Tour de Salvagny',
    phone: '06 24 63 94 45',
    email: 'ctripon@protonmail.com',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'lagnieu-mme-mr-roux-perrine-emmanuel',
    name: 'Mme & Mr ROUX Perrine & Emmanuel',
    addressLine: '283, Rue Trélacour',
    city: 'Lagnieu',
    phone: '06 72 13 49 20',
    email: 'perrine.queva@gmail.com',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'lentilly-mme-sherlock-rebecca-mr-de-perretti-adrien',
    name: 'Mme SHERLOCK Rébecca & Mr de PERRETTI Adrien',
    addressLine: '369, Route de Sain-Bel',
    city: 'Lentilly',
    phone: '06 74 73 31 59',
    email: 'rsh.adp@outlook.com',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'limonest-mme-collet-elodie',
    name: 'Mme COLLET Elodie',
    addressLine: '986, Route du Puy d\'Or',
    city: 'Limonest',
    phone: '06 16 49 01 08',
    email: 'eloflo2469@free.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'limonest-mr-martel-paul-andre',
    name: 'Mr MARTEL Paul-André',
    addressLine: '956, Route du Puy d\'Or',
    city: 'Limonest',
    phone: '07 83 21 18 77',
    email: 'pamartel@bonnet-associes.e',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'lissieu-mme-chaine-michele',
    name: 'Mme CHAINE Michèle',
    addressLine: '29, Chemin Neuf',
    city: 'Lissieu',
    phone: '06 12 82 33 94',
    email: 'nicopno@gmail.com',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'lyon-9-sport-dans-la-ville-mr-theis',
    name: 'Sport dans la Ville - Mr THEIS',
    addressLine: '15, Quai de la Gare d\'Eau',
    city: 'Lyon 9',
    phone: '06 18 85 25 26',
    email: 'atheis@sportdanslaville.com',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'massieux-clos-dulys',
    name: 'Clos duLys',
    addressLine: '244, Chemin de Chantegrillet',
    city: 'Massieux',
    phone: '06 07 14 53 82',
    email: 'winter.patrick@gmail.com',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'miribel-decibel-france',
    name: 'DECIBEL FRANCE',
    addressLine: '616, rue de la Dombes',
    city: 'Miribel',
    phone: '06 82 80 74 63',
    email: 'charlotte.pugnet@decibelfrance.com',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'miribel-mme-penon-vaudoyer',
    name: 'Mme PENON VAUDOYER',
    addressLine: 'Les Rêts - Les Echets',
    city: 'Miribel',
    phone: '06 60 65 92 39',
    email: 'sap2p@yahoo.fr',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'montanay-mr-blanc-manuel',
    name: 'Mr BLANC Manuel',
    addressLine: '544, Rue du Vieux Château',
    city: 'Montanay',
    phone: '06 84 94 28 33',
    email: 'manuelblanc@free.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'montluel-mme-rocheray-valery-mr-canales',
    name: 'Mme ROCHERAY Valéry & Mr CANALES',
    addressLine: '385, Rue des Ecorchats',
    city: 'Montluel',
    phone: '06 60 49 22 73',
    email: 'valerie.rocherayfaucon@gmail.com / canalesdaniel@yahoo.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'quincieux-mme-seon-sylvie',
    name: 'Mme SEON Sylvie',
    addressLine: '28, Route de Chasselay',
    city: 'Quincieux',
    phone: '06 41 20 05 68',
    email: 'martial.seon@laposte.net',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'reyrieux-a3-immo',
    name: 'A3+IMMO',
    addressLine: '1087, Route de Trévoux',
    city: 'Reyrieux',
    phone: '04 74 62 88 64',
    email: 'a3plusimmo@gmail.com',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'reyrieux-mme-bouvier-marie-claude',
    name: 'Mme BOUVIER Marie-Claude',
    addressLine: 'Chemin de Halage',
    city: 'Reyrieux',
    phone: '06 81 57 83 97',
    email: 'bouvier.katia@orange.fr',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'reyrieux-mr-saderne-bernard',
    name: 'Mr SADERNE  Bernard',
    addressLine: '1020, Route de Veissieux le Bas',
    city: 'Reyrieux',
    phone: '06 64 88 35 80',
    email: 'bsaderne@free.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'reyrieux-mr-sertelon-daniel',
    name: 'Mr SERTELON Daniel',
    addressLine: '110, Chemin de Sertelon',
    city: 'Reyrieux',
    phone: '06 88 09 98 14',
    email: 'daniel.sertelon@orange.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'reyrieux-societe-gabriel-sci-la-clarte-mr-geminet-jean-miche',
    name: 'Société Gabriel - SCI La Clarté - Mr GEMINET Jean-Michel',
    addressLine: 'ZI de Reyrieux - Rue des Garennes',
    city: 'Reyrieux',
    phone: '04 74 00 44 99',
    email: 'gabriel31@wanadoo.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'rillieux-la-pape-mme-mr-danjean-nathalie',
    name: 'Mme & Mr DANJEAN Nathalie',
    addressLine: '804, Chemin de Viralamande',
    city: 'Rillieux-La-Pape',
    phone: '06 15 47 90 25',
    email: 'nathalie.danjean@gmail.com',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'saint-bernard-mme-martin-sylvie',
    name: 'Mme MARTIN Sylvie',
    addressLine: '980, Chemin du Bois de Lys',
    city: 'Saint-Bernard',
    phone: '06 71 53 14 79',
    email: 'sylviealicemartin@outlook.fr',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'saint-bernard-mr-alvarez-thomas',
    name: 'Mr ALVAREZ Thomas',
    addressLine: '482, Chemin du Bois de Lys',
    city: 'Saint-Bernard',
    phone: '07 69 01 98 52',
    email: 'thomas.alvarez1@gmail.com',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'saint-cyr-au-mont-d-or-mme-mr-perona-yvan-segolene',
    name: 'Mme & Mr PERONA Yvan & Ségolène',
    addressLine: '25, Rue Ampère',
    city: 'Saint-Cyr-au-Mont d\'or',
    phone: '06 65 08 24 72',
    email: 'yvanperona@yahoo.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'saint-didier-de-formans-mme-pommatau',
    name: 'Mme POMMATAU',
    addressLine: '854, Chemin de la Gravière',
    city: 'Saint-Didier de Formans',
    phone: '06 75 02 97 99',
    email: 'lucienne.pommatau@gmail.com',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'saint-didier-de-formans-mr-attard',
    name: 'Mr ATTARD',
    addressLine: '334, Route d’Ars',
    city: 'Saint-Didier de Formans',
    phone: '06 28 69 94 79',
    email: 'jeanmarc@attardco.fr',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'saint-didier-au-mont-d-or-mme-mr-linage-anne-laure-benjamin',
    name: 'Mme & Mr LINAGE Anne-Laure & Benjamin',
    addressLine: '39, Chemin des Barres',
    city: 'Saint-Didier-au-Mont d\'Or',
    phone: '06 60 41 38 65',
    email: 'annelaureetbenjamin@gmail.com',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'saint-didier-au-mont-d-or-mr-dargaud-julien',
    name: 'Mr DARGAUD Julien',
    addressLine: '2, Rue de la Roche',
    city: 'Saint-Didier-au-Mont d\'Or',
    phone: '06 99 70 96 76',
    email: 'julien.drgd@gmail.com',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'saint-didier-au-mont-d-or-mr-lardon-philippe',
    name: 'Mr LARDON Philippe',
    addressLine: '35, Chemin des Barres',
    city: 'Saint-Didier-au-Mont d\'Or',
    phone: '06 63 52 09 37',
    email: 'philippe.lardon@gmail.com',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'saint-didier-au-mont-d-or-mr-parseghian-patrick-tigran',
    name: 'Mr PARSEGHIAN Patrick Tigran',
    addressLine: '37, Chemin des Barres',
    city: 'Saint-Didier-au-Mont d\'Or',
    phone: '06 11 14 40 00',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'saint-didier-au-mont-d-or-mr-rousset-laurent',
    name: 'Mr ROUSSET Laurent',
    addressLine: '22, Chemin de Crecy',
    city: 'Saint-Didier-au-Mont d\'Or',
    phone: '06 64 06 31 12',
    email: 'laurent.rousset@laposte.net',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'saint-jean-de-thurigneux-mme-bernard',
    name: 'Mme BERNARD',
    addressLine: '529, Chemin du Pontet',
    city: 'Saint-Jean de Thurigneux',
    phone: '06 73 16 34 41',
    email: 'marie-christine.bernard58@orange.fr',
    contracts: {ReportKind.filtreCompact, ReportKind.posteRelevage},
  ),
  Client(
    id: 'saint-romain-au-mont-d-or-mme-carnelli-sylvaine',
    name: 'Mme CARNELLI Sylvaine',
    addressLine: '4, Chemin du Petit Mont-Cindré',
    city: 'Saint-Romain-au-Mont d\'Or',
    phone: '06 51 55 17 71',
    email: 'scarnelli07@gmail.com',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'saint-romain-au-mont-d-or-mr-ngau-tang',
    name: 'Mr NGAU Tang',
    addressLine: '4, Chemin des Tuileries',
    city: 'Saint-Romain-au-Mont d\'Or',
    phone: '07 62 70 39 83',
    email: 'ngautang84@gmail.com',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'sainte-consorce-mr-thoinet-sebastien',
    name: 'Mr THOINET Sébastien',
    addressLine: '34, Chemin du Tronchil',
    city: 'Sainte-Consorce',
    phone: '06 67 69 27 96',
    email: 'sebastien_thoinet@hotmail.com',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'sainte-euphemie-mr-sanchez-yann',
    name: 'Mr SANCHEZ Yann',
    addressLine: '390, Route de Misérieux',
    city: 'Sainte-Euphémie',
    phone: '06 32 05 05 86',
    email: 'ysanchez@riseup.net',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'savigny-garage-paret',
    name: 'Garage PARET',
    addressLine: 'La Rochette',
    city: 'Savigny',
    phone: '06 86 49 55 67',
    email: 'jp.paret@garage-paret-renault.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'toussieux-mme-mr-tartavel-jean-marc',
    name: 'Mme & Mr TARTAVEL Jean-Marc',
    addressLine: 'Route de Trévoux',
    city: 'Toussieux',
    phone: '06 66 31 58 37',
    email: 'sylvietartavel@hotmail.fr',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'trevoux-mme-belaid',
    name: 'Mme BELAID',
    addressLine: '220, Route de Lyon',
    city: 'Trévoux',
    phone: '06 37 02 39 57',
    email: 'safy.elk@gmail.com',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'trevoux-mr-guilloux-mme-amirault',
    name: 'Mr GUILLOUX / Mme AMIRAULT',
    addressLine: '1570, Chemin d\'Arras',
    city: 'Trévoux',
    phone: '06 81 87 53 44 ou  06 24 08 73 62',
    email: 'a.oliveira@gpld.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'trevoux-mr-renfer',
    name: 'Mr RENFER',
    addressLine: '1570, Chemin d\'Arras',
    city: 'Trévoux',
    phone: '06 07 85 19 81',
    email: 'a.oliveira@gpld.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'trevoux-mr-thiriet-joel',
    name: 'Mr THIRIET Joël',
    addressLine: '30, Rue des Tours',
    city: 'Trévoux',
    phone: '06 75 02 97 99',
    email: 'thiriet.joel@orange.fr',
    contracts: {ReportKind.filtreCompact},
  ),
  Client(
    id: 'vancia-sci-9-fevrier-mr-julien-clement',
    name: 'SCI 9 Février - Mr JULIEN Clément',
    addressLine: '49, Chemin de Neyron - Vancia',
    city: 'Vancia',
    phone: '06 73 87 88 27',
    email: 'c.julien@patriarca.fr',
    contracts: {ReportKind.posteRelevage},
  ),
  Client(
    id: 'villefranche-sur-saone-a-3-immo-mme-gatt-carole',
    name: 'A 3+ IMMO - Mme GATT Carole',
    addressLine: '136, Rue de la République',
    city: 'Villefranche-Sur-Saône',
    phone: '04 74 62 88 64',
    email: 'carole.gatt@a3immo.com',
    contracts: {ReportKind.posteRelevage},
  ),];
